#!/bin/bash

TARGET_ARCH=aarch64-linux-gnu
TARGET_GCC_VERSION=5.4.0
TARGET_BINUTILS_VERSION=2.26.1
TARGET_NAME="arm64"
GCC_CONFIG_FLAGS="--enable-multiarch --disable-libquadmath --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-fix-cortex-a53-843419"
