#!/bin/bash

TARGET_ARCH=x86_64-linux-gnu
TARGET_GCC_VERSION=5.4.0
TARGET_BINUTILS_VERSION=2.26.1
TARGET_NAME="x86-64"
GCC_CONFIG_FLAGS="--enable-threads=posix --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --disable-vtable-verify --enable-libmpx --enable-plugin --with-arch-directory=amd64 --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic"
