#!/bin/bash

TARGET_ARCH=arm-linux-gnueabihf
TARGET_GCC_VERSION=5.4.0
TARGET_BINUTILS_VERSION=2.26.1
TARGET_NAME="armv7ubuntu"
GCC_CONFIG_FLAGS="--enable-multiarch --enable-multilib --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-mode=thumb --with-float=hard"
