#!/bin/bash

TARGET_ARCH=i686-linux-gnu
TARGET_GCC_VERSION=4.8.5
TARGET_BINUTILS_VERSION=2.25.1
TARGET_NAME="debian4-i686"
GCC_CONFIG_FLAGS="--disable-multiarch --with-cpu=generic --disable-libsanitizer --disable-libcilkrts --disable-linker-build-id --disable-gnu-unique-object --disable-libatomic"
