#!/bin/bash

TARGET_ARCH=x86_64-linux-gnu
TARGET_GCC_VERSION=4.9.3
TARGET_BINUTILS_VERSION=2.25.1
TARGET_NAME="debian4-x86-64"
GCC_CONFIG_FLAGS="--disable-multilib --with-tune=generic --disable-libsanitizer --disable-libcilkrts --disable-linker-build-id --disable-gnu-unique-object --disable-libatomic"
