#!/bin/bash

TARGET_ARCH=arm-linux-gnueabihf
TARGET_GCC_VERSION=4.8.5
TARGET_BINUTILS_VERSION=2.25.1
TARGET_NAME="rpi2"
GCC_CONFIG_FLAGS="--enable-multiarch --enable-multilib --with-cpu=cortex-a7 --with-tune=cortex-a7 --with-arch=armv7-a --with-fpu=neon-vfpv4 --with-mode=thumb --with-float=hard"
